#include "../include/bindings.hpp"

/**
 * @file names.cpp
 * @brief Definitions of naming constants for Python bindings.
 *
 * This file contains the storage definitions for global arrays used to name
 * the Python classes generated by the pybind11 module. It maps internal C++
 * types and series indices to their string representations exposed to Python.
 *
 * @authors Sobolev Y. A., Naumov A.U.
 */

/**
 * @brief Array of series class names.
 * Automatically generated from series_registry.def.
 */
constinit const char* series_names[OVERALL_SERIES_DEFINED] = {
#define SERIES_ENTRY(snake, camel) camel,
#define SERIES_LAST(snake, camel) camel
#include "../../src/include/series_registry.def"
#undef SERIES_ENTRY
#undef SERIES_LAST
};

/**
 * @brief Array of suffixes for standard numeric types.
 *
 * Used to distinguish bindings for different precisions and complex types.
 * - F32: float
 * - F64: double
 * - FLong: long double
 * - CF32: std::complex<float>
 * - CF64: std::complex<double>
 * - CFLong: std::complex<long double>
 */
constinit const char* available_types[OVERALL_ARB_TYPES] = {
    "F32",
    "F64",
    "FLong",
    "CF32",
    "CF64",
    "CFLong",
};