name: shanks-university
services:
  shanks-runner:
    stdin_open: true
    tty: true
    container_name: shanks-runner
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    depends_on:
      shanks-runner-mongodb:
        condition: service_healthy
    volumes:
      - ./backend/runner/config:/app/config
      - ./backend/runner/output:/app/output
    networks:
      - shanks-network

  shanks-runner-mongodb:
    image: mongo:latest
    container_name: shanks-runner-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - shanks-network

  shanks-client:
    container_name: shanks-client
    build:
      context: .
      dockerfile: frontend/client/Dockerfile
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 8080:8000
    depends_on:
      shanks-runner-mongodb:
        condition: service_healthy
    volumes:
      - ./frontend/client/:/app/
    networks:
      - shanks-network

volumes:
  mongo_data:

networks:
  shanks-network:
    driver: bridge
