#include "../include/bindings.hpp"

/**
 * @file names.cpp
 * @brief Definitions of naming constants for Python bindings.
 *
 * This file contains the storage definitions for global arrays used to name
 * the Python classes generated by the pybind11 module. It maps internal C++
 * types and series indices to their string representations exposed to Python.
 *
 * @authors Sobolev Y. A., Naumov A.U.
 */

/**
 * @brief Array of series class names.
 *
 * Used to generate the class names for series bindings in Python.
 * The order must match the `SeriesTuple` definition in `bind_series` function
 * within `bindings.hpp`.
 */
constinit const char* series_names[OVERALL_SERIES_DEFINED] = {
"AbsSinXMinus2DivPiSeries",
"ArcsinX2Series",
"ArcsinXMinusXSeries",
"ArcsinXSeries",
"ArcsinhXSeries",
"ArtanhX2Series",
"ArtanhXSeries",
"ArctanX2Series",
"ArctanX3Series",
"ArctanXSeries",
"BinSeries",
"CiXSeries",
"Cos3xMinus1DivXsquareSeries",
"CosSeries",
"CosSqrtXSeries",
"CosX2Series",
"CoshSeries",
"EXSeries",
"EighthPiMOneThirdSeries",
"ErfSeries",
"ExpMCosXSinsinXSeries",
"ExpSeries",
"ExpSquaredErfSeries",
"FivePiTwelveSeries",
"FourArctanSeries",
"FourLn2M3Series",
"HalfAsinTwoXSeries",
"HalfMinusSinxMultiPi4Series",
"HalfMultiLn1Div2Multi1MinusCosxSeries",
"IncompleteGammaFuncSeries",
"Inverse1mxSeries",
"InvSqrt1m4xSeries",
"KXSeries",
"LambertWFuncSeries",
"Ln1MinusX2Series",
"Ln1mxSeries",
"Ln1px4Series",
"Ln2Series",
"Ln13MinusLn7Div7Series",
"Ln1PlusX3Series",
"Ln1PlusSqrt1PlusXsquareMinusLn2Series",
"Ln1plusXDiv1plusX2Series",
"LnCosxSeries",
"LnSinxMinusLnXSeries",
"LnXPlusOneXMinusOneHalfedSeries",
"MFact1mxMp1InverseSeries",
"MeanSinhSinSeries",
"Minus3Div4OrXMinus3Div4Series",
"MinusOneNFactNInNSeries",
"MinusOneNedInNSeries",
"MinusOneQuarterSeries",
"MinusThreePlusLn3ThreeDividedTwoPlusTwoLn2Series",
"MinusXMinusPi4OrMinusPi4Series",
"OneDivSqrt2SinXDivSqrt2Series",
"OneDivTwoMinusXMultiThreePlusXSeries",
"OneMinusSqrt1minus4xDiv2xSeries",
"OneSeries",
"OneThirdPiSquaredMNineSeries",
"OneTwelfth3x2Pi2Series",
"OneTwelfthSeries",
"OneTwelfthX2Pi2Series",
"Pi3Series",
"Pi4Series",
"Pi8CosxSquareMinus1Div3CosxSeries",
"PiCubed32Series",
"PiFourMinusLn2HalfedSeries",
"PiMinus3pi4AndPiMinusXMinus3pi4Series",
"PiMinusX2Series",
"PiSeries",
"PiSixMinHalfSeries",
"PiSquared6MinusOneSeries",
"PiSquaredTwelveSeries",
"PiXMinusXSquareAndXSquareMinusThreePiXPlusTwoPiSquareSeries",
"PiXMultiE_XpiPlusEMinusXpiDividedE_XpiMinusEMinusXpiMinusOneSeries",
"RiemannZetaFuncSeries",
"RiemannZetaFuncXmin1DivRiemannZetaFuncXSeries",
"SeriesWithLnNumber1",
"SeriesWithLnNumber2",
"SiXSeries",
"SinSeries",
"SinX2Series",
"SinhSeries",
"SinhX2Series",
"Sqrt1plusXMinus1MinusXDiv2Series",
"Sqrt1plusXSeries",
"SqrtOneminusSqrtoneminusxDivXSeries",
"TenMinusXSeries",
"ThreeMinusPiSeries",
"TwoArcsinSquareXHalfedSeries",
"TwoDegreeXSeries",
"TwoLn2Series",
"X_1mx_SquaredSeries",
"XDiv1minX2Series",
"XDiv1minXSeries",
"XMinSqrtXSeries",
"XSeries",
"XTwoSeries",
"XTwoThroughtSquaresSeries",
"Xsquareplus3DivXsquareplus2multixMinus1Series",
};

/**
 * @brief Array of suffixes for standard numeric types.
 *
 * Used to distinguish bindings for different precisions and complex types.
 * - F32: float
 * - F64: double
 * - FLong: long double
 * - CF32: std::complex<float>
 * - CF64: std::complex<double>
 * - CFLong: std::complex<long double>
 */
constinit const char* available_types[OVERALL_ARB_TYPES] = {
    "F32",
    "F64",
    "FLong",
    "CF32",
    "CF64",
    "CFLong",
};
