#include "bridge.hpp"
#include "ffi_internal.hpp"
#include "series.hpp"
#include "series_base.hpp"
#include "series_acceleration.hpp"
#include "methods.hpp"
#include "utils.hpp"
#include "noise/noise_generator.hpp"
#include "filters/kolmogorov_zurbenko.hpp"
#include "filters/savitzky_golay.hpp"

// Generated by cxx-build
#include "shanks-unified/src/ffi/bridge.rs.h"

#include <complex>
#include <memory>
#include <string>
#include <vector>

namespace shanks::ffi::bridge {

// ----------------------------------------------------------------------------
// Conversion Helpers
// ----------------------------------------------------------------------------

template <typename T>
RealValue to_rv(const T& val) {
    auto sci = to_scientific(val);
    return RealValue{sci.mantissa, sci.exponent};
}

template <typename T>
ComplexValue to_cv(const std::complex<T>& val) {
    return ComplexValue{to_rv(val.real()), to_rv(val.imag())};
}

template <typename T>
IntervalValue to_iv(const intprec::interval<T>& val) {
    return IntervalValue{to_rv(val.lower()), to_rv(val.upper())};
}

template <typename T>
CIntervalValue to_civ(const std::complex<intprec::interval<T>>& val) {
    return CIntervalValue{to_cv(val.real()), to_cv(val.imag())};
}

// ----------------------------------------------------------------------------
// CSeries Implementation
// ----------------------------------------------------------------------------

template <typename T>
class CSeriesImpl : public CSeries {
    std::unique_ptr<shanks::series::series_base<T, size_t>> series;
    ::series_result<T> result;
    PrecisionType prec;

public:
    CSeriesImpl(std::unique_ptr<shanks::series::series_base<T, size_t>> s, PrecisionType p)
        : series(std::move(s)), prec(p) {
        result = series->generate(100); // Default generate 100
    }

    CSeriesImpl(::series_result<T> res, PrecisionType p)
        : result(std::move(res)), prec(p) {}

    PrecisionType precision_type() const override { return prec; }
    const void* raw_result() const override { return &result; }

    RawArr get_sn() const override { return convert_vec(result.Sn); }
    RawArr get_an() const override { return convert_vec(result.an); }

    RawArr get_deviation() const override {
        if (!series) {
            RawArr res;
            res.tag = ArrKind::Real;
            return res;
        }
        try {
            T limit = series->get_sum();
            std::vector<T> dev;
            dev.reserve(result.Sn.size());
            using std::abs;
            for (const auto& s : result.Sn) dev.push_back(abs(s - limit));
            return convert_vec(dev);
        } catch (...) {
            RawArr res;
            res.tag = ArrKind::Real;
            return res;
        }
    }

    RawValue get_limit() const override {
        if (!series) {
            RawValue res;
            res.tag = ValueKind::Real;
            return res;
        }
        try {
            T limit = series->get_sum();
            return convert_val(limit);
        } catch (...) {
            RawValue res;
            res.tag = ValueKind::Real;
            return res;
        }
    }

    std::unique_ptr<CSeries> apply_noise(rust::Str name, rust::Str params_json) const override {
        // Just return a copy for now or implement noise if available
        return std::make_unique<CSeriesImpl<T>>(result, prec);
    }

    std::unique_ptr<CSeries> run_algo(rust::Str name, rust::Str params_json) const override {
        std::string s_name(name);
        auto keys = shanks::algos::transformation_registry_metadata::get_keys();
        size_t idx = 0;
        bool found = false;
        for (; idx < keys.size(); ++idx) {
            if (keys[idx] == s_name) { found = true; break; }
        }
        if (!found) throw std::runtime_error("Algorithm not found");

        auto algo = shanks::algos::transformation_registry<T, size_t>::create_by_index(idx);
        auto accelerated = (*algo)(result.Sn.size(), 1, result);

        ::series_result<T> acc_res;
        acc_res.Sn = {accelerated};
        acc_res.an = {accelerated};
        return std::make_unique<CSeriesImpl<T>>(std::move(acc_res), prec);
    }

    RawArr filter(rust::Str name, rust::Str params_json) const override {
        return convert_vec(result.Sn); // Stub
    }

private:
    RawArr convert_vec(const std::vector<T>& vec) const {
        RawArr res;
        auto size = vec.size();
        if constexpr (is_complex_interval_v<T>) {
            res.tag = ArrKind::CInterval;
            res.r1.reserve(size); res.r2.reserve(size); res.r3.reserve(size); res.r4.reserve(size);
            for (const auto& v : vec) {
                auto civ = to_civ(v); 
                res.r1.push_back(civ.inf.real); res.r2.push_back(civ.sup.real);
                res.r3.push_back(civ.inf.imag); res.r4.push_back(civ.sup.imag);
            }
        } else if constexpr (is_complex_v<T>) {
            res.tag = ArrKind::Complex;
            res.r1.reserve(size); res.r2.reserve(size);
            for (const auto& v : vec) {
                auto cv = to_cv(v);
                res.r1.push_back(cv.real); res.r2.push_back(cv.imag);
            }
        } else if constexpr (is_interval_v<T>) {
            res.tag = ArrKind::Interval;
            res.r1.reserve(size); res.r2.reserve(size);
            for (const auto& v : vec) {
                auto iv = to_iv(v);
                res.r1.push_back(iv.inf); res.r2.push_back(iv.sup);
            }
        } else {
            res.tag = ArrKind::Real;
            res.r1.reserve(size);
            for (const auto& v : vec) res.r1.push_back(to_rv(v));
        }
        return res;
    }

    RawValue convert_val(const T& val) const {
        RawValue res;
        if constexpr (is_complex_interval_v<T>) {
            res.tag = ValueKind::CInterval;
            auto civ = to_civ(val);
            res.r1 = civ.inf.real; res.r2 = civ.sup.real;
            res.r3 = civ.inf.imag; res.r4 = civ.sup.imag;
        } else if constexpr (is_complex_v<T>) {
            res.tag = ValueKind::Complex;
            auto cv = to_cv(val);
            res.r1 = cv.real; res.r2 = cv.imag;
        } else if constexpr (is_interval_v<T>) {
            res.tag = ValueKind::Interval;
            auto iv = to_iv(val);
            res.r1 = iv.inf; res.r2 = iv.sup;
        } else {
            res.tag = ValueKind::Real;
            res.r1 = to_rv(val);
        }
        return res;
    }
};

// ----------------------------------------------------------------------------
// Factory Functions
// ----------------------------------------------------------------------------

std::unique_ptr<CSeries> mk_series(rust::Str name, rust::Str precision, rust::Str params_json) {
    std::string s_name = std::string(name);
    std::string s_prec = std::string(precision);
    PrecisionType pt;
    if (!parse_precision(s_prec.c_str(), pt)) throw std::runtime_error("Invalid precision");

    auto names = shanks::series::series_registry_metadata::get_names();
    size_t idx = 0;
    bool found = false;
    for (; idx < names.size(); ++idx) {
        if (names[idx] == s_name) { found = true; break; }
    }
    if (!found) throw std::runtime_error("Series not found");

    switch (pt) {
#ifndef SHANKS_SKIP_PRECISION
        case PrecisionType::F64: return std::make_unique<CSeriesImpl<double>>(shanks::series::series_registry<double, size_t>::create(idx, 1.0), pt);
#endif
        case PrecisionType::Arb: return std::make_unique<CSeriesImpl<mpfr::mpreal>>(shanks::series::series_registry<mpfr::mpreal, size_t>::create(idx, 1.0), pt);
        default: 
#ifdef SHANKS_SKIP_PRECISION
            if (pt == PrecisionType::F64) throw std::runtime_error("F64 precision disabled in debug build (SHANKS_SKIP_PRECISION)");
#endif
            throw std::runtime_error("Precision not yet implemented in bridge");
    }
}

std::unique_ptr<CSeries> apply_noise(const CSeries& series, rust::Str name, rust::Str params_json) {
    return series.apply_noise(name, params_json);
}

std::unique_ptr<CSeries> run_algo(const CSeries& series, rust::Str name, rust::Str params_json) {
    return series.run_algo(name, params_json);
}

RawArr get_sn(const CSeries& series) { return series.get_sn(); }
RawArr get_an(const CSeries& series) { return series.get_an(); }
RawArr get_deviation(const CSeries& series) { return series.get_deviation(); }
RawValue get_limit(const CSeries& series) { return series.get_limit(); }
RawArr filter(const CSeries& series, rust::Str name, rust::Str params_json) { return series.filter(name, params_json); }

} // namespace shanks::ffi::bridge

namespace shanks::ffi::bridge {

rust::Vec<rust::String> list_series() {
    rust::Vec<rust::String> res;
    // For now, return a static list or query series_registry if possible
    // Note: series_registry<double, size_t>::get_names() etc.
    res.push_back("PiSeries");
    res.push_back("Ln2Series");
    res.push_back("ZetaSeries");
    res.push_back("ExpSeries");
    res.push_back("AtanSeries");
    res.push_back("BinSeries");
    return res;
}

rust::Vec<rust::String> list_accels() {
    rust::Vec<rust::String> res;
    res.push_back("Shanks Transformation");
    res.push_back("Wynn's Epsilon Algorithm");
    res.push_back("Levin's Transformation");
    res.push_back("Richardson Extrapolation");
    res.push_back("Anderson's acceleration algorithm");
    return res;
}

rust::Vec<rust::String> list_precisions() {
    rust::Vec<rust::String> res;
    res.push_back("F64");
    res.push_back("Arb256");
    res.push_back("Arb512");
    res.push_back("CF64");
    res.push_back("CArb256");
    return res;
}

rust::Vec<rust::String> list_noises() {
    rust::Vec<rust::String> res;
    res.push_back("None");
    res.push_back("Gaussian");
    res.push_back("Uniform");
    return res;
}

rust::Vec<rust::String> list_noise_methods() {
    rust::Vec<rust::String> res;
    res.push_back("Additive");
    res.push_back("Multiplicative");
    return res;
}

} // namespace shanks::ffi::bridge
