name: Build vizrd

on:
  push:
    branches: ["main", "vizrd"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust Nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-x86_64-pc-windows-gnu

      # 2. Setup MSYS2 with path inheritance
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          release: false
          update: false
          path-type: inherit
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-gmp
            mingw-w64-x86_64-mpfr
            mingw-w64-x86_64-eigen3
            mingw-w64-x86_64-gsl
            mingw-w64-x86_64-ccache

      - name: Cache C++ (ccache)
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-
          save-always: true

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "vizrd"

      - name: Build Rust Frontend (vizrd.exe)
        run: |
          cd vizrd
          cargo build --release

      - name: Prepare Archive Folder
        run: |
          mkdir vizrd-windows
          cp vizrd/target/release/vizrd.exe vizrd-windows/
          cp -r vizrd/config vizrd-windows/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vizrd-windows
          path: vizrd-windows/
